sh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shshop.public.sites import sh_site
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shadmin/", sh_site.urls),
    path("", include("shshop.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/", include("api.urls")),
    # 3. coreapi文档路径
    path("docs/", include_docs_urls(title="接口测试平台API文档", description="这个是接口平台的文档")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shshop/module/cart/urls.py
from django.urls import path
from shshop.module.cart import views

urlpatterns = [
    path("", views.ShShopingCartListView.as_view(), name="carts"),
    path("add/", views.ShShopingCartCreateView.as_view(), name="add_cart"),
    path("update/num/", views.ShShopingCartUpdateView.as_view(), name="update_cart")
]

shshop/module/goods/urls.py
from django.urls import path
from shshop.module.goods import views

urlpatterns = [
    path("", views.ShShopSPUListView.as_view(), name="spus"),
    path("cate/<int:pk>/", views.ShShopCategoryDetailView.as_view(), name="cate_detail"),
    path("search/", views.SearchTemplateView.as_view(), name="search"),
    path("spu/<int:pk>/", views.ShShopSPUDetailView.as_view(), name="spu_detail"),
]

shshop/module/payment/urls.py
from django.urls import path
from shshop.module.payment import views


urlpatterns = [
    path("", views.CashRegisterTemplateView.as_view(), name="cash_register"),
    path("paynow/", views.PayNowView.as_view(), name="pay_now"),

]

shshop/module/post/urls.py
from django.urls import path
from shshop.module.post import views

urlpatterns = [
    # path("", views.ShShopingpostListView.as_view(), name="posts"),
    path("", views.POST, name="posts"),
    # path("add/", views.ShShopingpostCreateView.as_view(), name="add_post"),
    # path("update/num/", views.ShShopingpostUpdateView.as_view(), name="update_post")
]

shshop/urls.py
from django.urls import path, include

app_name = "shshop"

urlpatterns = [
    path("", include('shshop.public.urls')),
    path("user/", include('shshop.module.user.urls')),
    path("goods/", include('shshop.module.goods.urls')),
    path("cart/", include('shshop.module.cart.urls')),
    path("post/", include('shshop.module.post.urls')),
    path("order/", include('shshop.module.order.urls')),
    path("comments/", include('shshop.module.comments.urls')),
    path("article/", include('shshop.module.article.urls')),
	path("payment/", include('shshop.module.payment.urls')),
]

shshop/models.py
from django.db import models

# Create your models here.
from shshop.public.models import (ShMenu, ShPermission, ShBanner,
                                     ShUpload)

from shshop.module.user.models import (UserInfo, ShUserBalanceLog,
                                          ShShopAddress)

from shshop.module.goods.models import (ShShopCategory, ShShopSPU,
                                           ShShopSpec, ShShopSpecOption,
                                           ShShopSKU, ShSPUCarousel)

from shshop.module.cart.models import ShShopingCart
from shshop.module.post.models import GoodPost
from shshop.module.order.models import ShShopOrderInfo, ShShopOrderSKU
from shshop.module.comments.models import ShOrderInfoComments
from shshop.module.stats.models import ShIPAddress, ShStats
from shshop.module.article.models import ShArticleCategory, ShArticle, ShArticleTags

shshop/module/cart/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :cart.py
@说明    :购物车模型

'''

from django.db import models
from django.contrib.auth import get_user_model

from shshop.public.abstract import AbstractModel
from shshop.models import ShShopSKU

User = get_user_model()


class ShShopingCart(AbstractModel):
    """ 购物车数据模型 """
    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="用户")
    sku = models.ForeignKey(ShShopSKU, on_delete=models.PROTECT, verbose_name="商品sku")
    num = models.PositiveIntegerField(default=0, verbose_name="数量")

    class Meta:
        verbose_name = '购物车'
        verbose_name_plural = verbose_name
        constraints = [
            models.UniqueConstraint(fields=['owner', 'sku'], name='unique_owner_sku')
        ]

    def __str__(self):
        return f'{self.owner}{self.sku}'

    @classmethod
    def get_cart_count(cls, user):
        # 当前用户的购物车商品数量
        return sum(list(cls.objects.filter(owner=user).values_list('num', flat=True)))

shshop/module/comments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from shshop.public.abstract import ContentTypeAbstract

User = get_user_model()


class ShOrderInfoComments(ContentTypeAbstract):
    """ 评论 """
    class CommentChoices(models.IntegerChoices):
        GOOD = 5, _('好评')
        SO = 3, _('中评')
        BAD = 1, _('差评')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    content = models.CharField("留言内容", max_length=200)
    comment_choices = models.PositiveSmallIntegerField(
        default=5,
        choices=CommentChoices.choices,
        verbose_name="评分"
    )

    class Meta(ContentTypeAbstract.Meta):
        ordering = ['-add_date']
        verbose_name = "商品评价"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

shshop/module/cart/forms.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm

from shshop.models import ShShopingCart

class ShShopingCartForm(ModelForm):

    class Meta:
        model = ShShopingCart
        fields = ['sku', 'num']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

shshop/module/comments/forms.py
from django import forms

from shshop.models import ShOrderInfoComments


class ShOrderInfoCommentsModelForm(forms.ModelForm):

    class Meta:
        model = ShOrderInfoComments
        fields = ('content', 'comment_choices', 'object_id')
        widgets = {
            'content': forms.Textarea(attrs={"class":"textarea","rows": 5,  "placeholder":"请如实发表您对该商品的感受..."}),
        }

api/goods/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.response import Response
from shshop.module.goods.models import (ShShopCategory, ShShopSPU,
                                           ShShopSpec, ShShopSpecOption,
                                           ShShopSKU, ShSPUCarousel)
from .serializers import Model1Serializer, Model2Serializer,SkuallSerializer
from rest_framework.filters import OrderingFilter
from rest_framework import mixins, viewsets
class Gooda(viewsets.GenericViewSet, mixins.ListModelMixin):
    queryset = ShShopSKU.objects.all()
    serializer_class = SkuallSerializer
    filter_backends = [OrderingFilter]
    ordering_fields = ['price']

class Goods(APIView):
    def get(self, request):
        spu = ShShopSPU.objects.all()
        sku = ShShopSKU.objects.all()
        model1_serializer = Model1Serializer(spu, many=True)
        skuallSerializer=SkuallSerializer(sku, many=True)
        return Response(skuallSerializer.data)

shshop/module/article/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :views.py
@说明    :用户消息视图
@时间    :2023/03/24 15:04:52
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from shshop.models import ShArticle, ShArticleCategory, ShArticleTags


class ArticleContext:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cates'] = self.get_cates()
        context['tags'] = self.get_tags()
        # context['archive'] = ShArticle.get_archive()
        context['tags_classes'] = ['is-danger', 'is-info', 'is-success', 'is-primary', 'is-light', 'is-black']
        return context

    def get_cates(self):
        return ShArticleCategory.objects.all()

    def get_tags(self):
        return ShArticleTags.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

    def get_stats(self, object_id):
        return ShArticle.get_stats(self.request, object_id)


class ShArticleListView(ArticleContext, ListView):
    """ 用户消息列表 """

    model = ShArticle
    template_name = "shshop/article/article_list.html"
    paginate_by = 15


class ShArticleDetailView(ArticleContext, DetailView):
    """ 用户消息详情 """
    model = ShArticle
    template_name = "shshop/article/article_detail.html"
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.pv = self.get_stats(obj.id).pv
        obj.uv = self.get_stats(obj.id).uv
        return obj


class ShArticleCategoryListView(ArticleContext, SingleObjectMixin, ListView):
    """ 分类用户消息列表 """

    paginate_by = 15
    template_name = "shshop/article/article_list.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.get_cates())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cate'] = self.object
        return context

    def get_queryset(self):
        queryset = self.object.sharticle_set.all()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

shshop/module/cart/views.py
from django.views.generic import CreateView, ListView, View
from django.db.models import F
from django.db.utils import IntegrityError
from django.contrib import messages
from django.urls import reverse_lazy
from shshop.models import ShShopingCart, ShShopAddress
from shshop.public.mixins import (
    JsonableResponseMixin, JsonLoginRequiredMixin, JsonResponse,
    LoginRequiredMixin
)


class ShShopingCartCreateView(JsonLoginRequiredMixin, JsonableResponseMixin, CreateView):
    """ 加入购物车 """
    model = ShShopingCart
    fields = ['sku', 'num']
    success_url = reverse_lazy('shshop:carts')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        try:
            self.object = form.save()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
        except IntegrityError:
            carts = ShShopingCart.objects.filter(owner=self.request.user, sku=form.cleaned_data['sku'])
            carts.update(num=F('num')+int(form.cleaned_data['num']))
            self.object = carts.first()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
            return JsonResponse({'pk': self.object.id, 'code': 'ok', 'message': '已成功加入购物车！'}, json_dumps_params={'ensure_ascii': False})
        return super().form_valid(form)


class ShShopingCartListView(LoginRequiredMixin, ListView):

    template_name = "shshop/cart/carts.html"
    context_object_name = "carts"

    def get_queryset(self):
        queryset = ShShopingCart.objects.filter(owner=self.request.user)
        total = 0
        carts = []
        for cart in queryset:
            cart_dict = {}
            cart_dict['id'] = cart.id
            cart_dict['title'] = cart.sku.spu.title
            cart_dict['sku_id'] = cart.sku.id
            cart_dict['cover_pic'] = cart.sku.cover_pic.url
            cart_dict['options'] = list(cart.sku.options.values('name', 'spec__name'))
            cart_dict['price'] = cart.sku.price.to_eng_string()
            cart_dict['stock'] = cart.sku.stock
            cart_dict['sales'] = cart.num
            cart_dict['total_price'] = cart.num * cart.sku.price
            carts.append(cart_dict)
            total += cart.num * cart.sku.price
        return carts


class ShShopingCartUpdateView(JsonLoginRequiredMixin, View):
    """ 修改购物车数量 """

    def post(self, request, *args, **kwargs):
        cleaned_data = request.POST
        carts = ShShopingCart.objects.filter(owner=self.request.user, id=int(cleaned_data['id']))
        # 修改
        if carts.exists() and cleaned_data.get('actions') == 'update':
            carts.update(num=int(cleaned_data['num']))
            return JsonResponse({'code':'ok', 'message': '修改成功！'})
        # 删除
        elif carts.exists() and cleaned_data.get('actions') == 'delete':
            carts.delete()
            return JsonResponse({'code':'ok', 'message': '删除成功！'})
        else:
            return JsonResponse({'code':'err', 'message': '该购物不存在！'})

shshop/module/comments/views.py
from django.contrib.contenttypes.models import ContentType
from django.http.response import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages

from shshop.models import ShShopSKU, ShShopOrderSKU
from shshop.templatetags.shop_tags import commented_func
from shshop.module.order.views import ShShopOrderInfoDetailView
from shshop.module.comments.forms import ShOrderInfoCommentsModelForm


class ShOrderInfoCommentsFormView(ShShopOrderInfoDetailView):

    template_name = "shshop/comments/comments_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ShOrderInfoCommentsModelForm()
        return context

    def post(self, request, *args, **kwargs):

        # 判断评论时机
        if self.get_object().pay_status != 4:
            raise Http404

        form = ShOrderInfoCommentsModelForm(request.POST)
        content_type = ContentType.objects.get_for_model(ShShopSKU)
        form.instance.content_type = content_type
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            # 修改评论标志
            oskus = ShShopOrderSKU.objects.filter(
                    order=self.get_object(), sku__id=form.cleaned_data['object_id']
                )
            oskus.update(is_commented=True)
            # 修改订单状态
            if commented_func(self.get_object()):
                obj = self.get_object()
                obj.pay_status = 5
                obj.save()
            messages.add_message(request, messages.SUCCESS, f'评价发表成功！')
        return HttpResponseRedirect(f'{reverse("shshop:spu_detail", args=[oskus.first().sku.spu.id])}?tabsActive=comment')

shshop/module/order/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib import messages


from shshop.config.settings import sh_settings
from shshop.public.mixins import LoginRequiredMixin
from shshop.models import ShShopOrderInfo


class ShshopOrderInfoListView(LoginRequiredMixin, ListView):
    """ 订单列表 """
    model = ShShopOrderInfo
    template_name = "shshop/order/order_list.html"
    context_object_name = "order_list"
    paginate_by = sh_settings.USER_ORDERINFO_PAGINATE_BY
    paginate_orphans = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.request.GET.get('status') if self.request.GET.get('status') else ''
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-add_date').filter(owner=self.request.user)
        cleaned_data = self.request.GET.dict()
        if cleaned_data and (cleaned_data.get('status') in ['1', '2', '3', '4', '5', '6']):
            queryset = queryset.filter(pay_status=int(cleaned_data['status']))
        return queryset

    def post(self, request, *args, **kwargs):
        orders = ShShopOrderInfo.objects.filter(owner=request.user, order_sn=request.POST['order_sn'])
        orders.update(pay_status=4)
        messages.add_message(request, messages.SUCCESS, f'订单{orders.first()}已确认收货！')
        return HttpResponseRedirect(f"{request.path}?status=4")


class ShShopOrderInfoDetailView(LoginRequiredMixin, DetailView):
    """ 订单结算支付 """

    model = ShShopOrderInfo
    template_name = "shshop/order/order_detail.html"
    context_object_name = "order"
    slug_field="order_sn"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_methods'] = self.get_pay_methods()
        return context

    def get_pay_methods(self):
        pay_methods = ShShopOrderInfo.get_pay_method()
        pay_list = [
            {
                'value': 1,
                'name': pay_methods[1],
                'icon': "/static/shshop/img/hdpay.svg",
                'is_default': False,
            },
            {
                'value': 4,
                'name': pay_methods[4],
                'icon': "/static/shshop/img/ye.svg",
                'is_default': False,
            }
        ]
        return pay_list


class ShShopOrderInfoUserDetailView(ShShopOrderInfoDetailView):

    template_name = "shshop/order/user_order_detail.html"

shshop/templates/shshop/goods/spu_detail.html
{% extends 'shshop/base_site.html' %}

{% load static shop_tags %}

{% block title %}{{ spu.title }}{% endblock %}

{% block extrastyle %}
    <script src="{% static 'shshop/js/axios.min.js' %}"></script>
    <script src="{% static 'shshop/js/request.js' %}"></script>
    <style>
        [v-cloak] {
            display: none !important;
        }
        .is-active .al img {
            filter: grayscale(0%);
           /* border: solid 1px rebeccapurple;*/
        }
        .carousel{border: solid 1px rgba(224, 224, 224, 0.232);}
        .carousel-indicator{
            align-items: center;
            border-top: solid 1px rgba(224, 224, 224, 0.232);
            padding: 0;
            background-color: #fff;
        }
        .al img {
            filter: grayscale(100%);
        }

    </style>
{% endblock %}

{% block breadcrumb %}
<div class="container">
  <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'shshop:home' %}">首页</a></li>
      <li><a href="{% url 'shshop:cate_detail' spu.category.first.parent.id %}">{{ spu.category.first.parent.name }}</a></li>
      <li><a href="{% url 'shshop:cate_detail' spu.category.first.id %}">{{ spu.category.first.name }}</a></li>
      <li class="is-active"><a href="#" aria-current="page">{{ spu.title }}</a></li>
    </ul>
  </nav>
</div>
{% endblock %}


{% block content %}
{{ skus|json_script:"skus-data" }}
{{ specs|json_script:"specs-data" }}
{{ current_ops|json_script:"current-ops-data" }}
<div class="container" id="spuDetail" v-cloak>
    <div class="columns">
        <div class="column is-3">
            <div class="box1 is-radiusless is-shadowless">
                <b-carousel :indicator-inside="false">
                    <b-carousel-item v-for="(item, i) in goods.banners" :key="i">
                        <b-image class="image" ratio="1by1" :src="getImgUrl(item)"></b-image>
                    </b-carousel-item>
                    <template #indicators="props">
                        <b-image class="al image" :src="getImgUrl(goods.banners[props.i])"></b-image>
                    </template>
                </b-carousel>
            </div>
        </div>
        <div class="column">
            <h1 class="is-size-5 has-text-justified has-text-weight-bold mb-2">{{ spu.title }}</h1>
            <div class="box is-marginless is-radiusless has-background-primary-dark has-text-white-ter">
                <div class="is-flex is-justify-content-space-between is-align-items-center">
                    <div>
                        <span class=" is-size-7"> 原价：¥ <del>{$ goods.org_price $}</del></span>
                        <h1 class=" is-size-4">¥ {$ goods.price $}</h1>
                    </div>
                    <div class=" has-text-centered">
                        {$ goods.sales $}
                        <h1>销量</h1>
                    </div>
                </div>
            </div>

            {% comment %} 规格 {% endcomment %}
            <div class="box is-radiusless is-shadowless is-marginless" v-if="currentOps.length > 0" >
                <div class="is-flex is-flex-direction-column is-justify-content-space-around" style="min-height:80px">
                    <div class="is-flex" v-for="spec, index in specs" :key="index">
                        <span class="is-size-7 mr-3">{$ spec.spec $}:</span>
                        <b-radio-button v-for="op, i in spec.options" :key="op"
                            @click.native=""
                            v-model="currentOps[index]"
                            :native-value="op"
                            size="is-small"
                            class="mr-2 is-radiusless is-shadowless"
                            type="is-danger is-light is-outlined">
                            <span>{$ op $}</span>
                        </b-radio-button>
                    </div>
                </div>
            </div>

            <!-- 数量 -->
            <div class="box is-flex is-align-items-center is-radiusless is-shadowless is-marginless">
                <div class="is-size-7 mr-3">数量:</div>
                <div>
                    <b-field>
                        <b-numberinput
                            controls-position="compact"
                            min="1"
                            :max="stock"
                            v-model="num"
                            size="is-small"
                            :editable="false">
                        </b-numberinput>
                    </b-field>
                </div>
                <div class="ml-3">(库存{$ stock $})</div>
            </div>

            <!-- 操作 -->
            <div class="buttons box is-radiusless">
                <b-button
                    type="is-primary"
                    @click="addCart"
                    :disabled="stock ? false : true">加入购物车
                </b-button>
                <b-button
                    type="is-primary"
                    :disabled="stock ? false : true"
                    @click="cashRegister"
                    outlined>
                    立即购买
                </b-button>
            </div>

            {% comment %} 商品详情及评论 {% endcomment %}
            <div class="box is-radiusless">
                <b-tabs class="block" @input="tabsChange" v-model="activeTab">
                    <b-tab-item label="商品详情" value="content">
                        <div class="content">{{ spu.content|safe }}</div>
                    </b-tab-item>
                    <b-tab-item label="商品评价" value="comment">
                        <div class="is-flex is-justify-content-space-between p-2">
                            <div class="">满意度：{{ like_rate }}%</div>
                            <div class="is-flex is-align-items-center">
                                <span> 评分：</span>
                                <b-rate
                                    :value="{{ score }}"
                                    disabled
                                    custom-text="{{ score }}分">
                                </b-rate>
                            </div>
                        </div>
                        <div class=" dropdown-divider"></div>

                        {% for comment in page_comments %}
                            <article class="media">
                                <figure class="media-left">
                                    <p class="image is-32x32">
                                        <img class="is-rounded" src="{{ comment.owner.shuserinfo.avatar.url }}">
                                    </p>
                                </figure>
                                <div class="media-content">
                                    <p>
                                        {{ comment.owner.username }}
                                        <b-rate size="is-small" :value="{{ comment.comment_choices }}" disabled custom-text="{{ comment.comment_choices }}分"></b-rate>
                                    </p>
                                    <p class=" is-size-7">{{ comment.add_date|timesince }}前</p>
                                    <p class=" has-text-grey-light">{{ comment }}</p>
                                </div>
                            </article>
                        {% empty %}
                        <p class=" has-text-centered has-text-danger mt-6">还没有任何评价内容哦！</p>
                        {% endfor %}

                        {% if page_comments %}
                        <nav class="pagination is-centered1 is-small" role="navigation" aria-label="pagination">
                            {% if page_comments.has_previous %}
                            <a class="pagination-previous" href="?page={{ page_comments.previous_page_number }}&tabsActive=comment">Previous</a>
                            {% endif %}
                            {% if page_comments.has_next %}
                            <a class="pagination-next" href="?page={{ page_comments.next_page_number }}&tabsActive=comment">Next page</a>
                            {% endif %}
                            <ul class="pagination-list">
                                {% for p in page_obj.paginator.get_elided_page_range %}
                                    {% if p != '...' %}
                                    <li><a href="?page={{ p }}&tabsActive=comment" class="pagination-link {% if page_comments.number == p %} is-current {% endif %}" {% if page_comments.number == p %}aria-current="page"{% endif %} aria-label="Goto page {{ p }}">{{ p }}</a></li>
                                    {% else %}
                                    <li><span class="pagination-ellipsis">&hellip;</span></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </nav>
                        {% endif %}

                    </b-tab-item>
                </b-tabs>
            </div>
        </div>
        <div class="column is-2">
            <h1 class="has-text-centered has-background-white pt-3 is-size-6 pb-3 has-text-weight-bold">关注排行</h1>
            <div class=" dropdown-divider is-marginless"></div>
            {% for spu in hot_spus %}
            <div class="has-background-white">
                {% spu_box spu %}
            </div>
            <div class="dropdown-divider"></div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

{% block vue %}
    <script>
        var skus = JSON.parse(document.getElementById('skus-data').textContent);
        var specs = JSON.parse(document.getElementById('specs-data').textContent);
        var currentOps = JSON.parse(document.getElementById('current-ops-data').textContent);
        var spuDetail = new Vue({
            el: '#spuDetail',
            delimiters: ['{$', '$}'],
            data:{
                skus:skus,
                specs:specs,
                currentOps: currentOps,
                goods: null,
                num: 1,
                isDisabled: false,
                stock:0,

                activeTab: '{{ tabs_active }}'
            },
            created(){
                this.goods = this.currentOps.length > 0 ? this.skus[this.currentOps.join(',')] : this.skus[this.currentOps]
                this.stock = this.goods.stock
            },
            methods: {
                getImgUrl(value) {
                    return `${value}`
                },
                // 加入购物车
                addCart(){
                    const sendData = new FormData()
                    sendData.append('sku', this.goods.sku_id)
                    sendData.append('num', this.num)
                    request({
                        method: 'post',
                        url: '{% url "shshop:add_cart" %}',
                        headers: {'Accept': 'application/json'},
                        data: sendData
                    }).then(res => {
                        if (res.data.code == 'ok') {
                            navbar.toastMessage('is-success', res.data.message)
                            location.reload()
                        }else{
                            navbar.toastMessage('is-danger', res.data.message)
                        }
                    })
                },

                // 立即购买
                cashRegister(){
                    location.href = `{% url 'shshop:cash_register' %}?skuID=${this.goods.sku_id}&num=${this.num}`
                },

                // tabs
                tabsChange(value){
                    location.href = `{{ request.path }}?tabsActive=${value}`
                }
            },
            watch:{
                currentOps:{
                    handler: function(val, oldval){
                        let strVal = val.join();
                        goods = this.skus[strVal]
                        if (goods) {
                            this.isDisabled = false
                            this.stock = goods.stock
                            this.goods = {
                                'sku_id': this.skus[strVal]['sku_id'],
                                'price': goods.price,
                                'org_price': goods.org_price,
                                'stock': this.stock,
                                'sales': goods.sales,
                                'cover_pic': goods.cover_pic,
                                'banners': goods.banners
                            }
                            console.log(this.goods)
                        }else if (goods == undefined) {
                            this.stock = 0
                            this.isDisabled = true
                        }
                    },
                    deep: true,

                }
            }
        })
    </script>
{% endblock %}