api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import *
from rest_framework.urlpatterns import format_suffix_patterns
from .auth.views import CustomAuthToken, RegisterView, UserAvatarUpdateView
from .auth.user import UserInfoMenmberViewset,ShShopAddressViewSet
from .goods.views import Gooda,Goods
router = DefaultRouter()
router.register('usermember', UserInfoMenmberViewset, basename='user')
router.register('useraddress', ShShopAddressViewSet, basename='address')
router.register(r'goods', Gooda, basename='goodsviewset')


urlpatterns = [
    path('public/menu/', MenuList.as_view(), name='menu'),
    path('public/permission/', PermissionList.as_view(), name='permission'),
    path('public/banner/', BannerList.as_view(), name='banner'),
    path('public/upload/', UploadList.as_view(), name='upload'),
    path('user/info/', UserInfoList.as_view(), name='userinfo'),
    path('user/balance/log/', UserBalanceLogList.as_view(), name='userbalancelog'),
    path('user/shop/address/', ShopAddressList.as_view(), name='shopaddress'),
    path('goods/category/', ShopCategoryList.as_view(), name='shopcategory'),
    path('goods/cspu/', ShopSPUCList.as_view(), name='shopspu'),#可查找分类 ?ctg= 如http://116.63.12.26/api/goods/cspu/?ctg=8
    path('goods/spu/', ShopSPUList.as_view(), name='shopspu'),#可查找owner ?uid=
    path('goods/spec/', ShopSpecList.as_view(), name='shopspec'),
    path('goods/spec/option/', ShopSpecOptionList.as_view(), name='shopspecoption'),
    path('goods/sku/', ShopSKUList.as_view(), name='shopsku'), #可查找spu ?spu=

    path('goods/spu/carousel/', SPUCarouselList.as_view(), name='spucarousel'),
    path('cart/shoppingcart/', ShoppingCart.as_view(), name='shoppingcart'),
    path('order/info/', ShopOrderInfoList.as_view(), name='shoporderinfo'),
    path('order/sku/', ShopOrderSKUList.as_view(), name='shopordersku'),
    path('comments/orderinfo/', OrderInfoCommentsList.as_view(), name='orderinfocomments'),
    path('goodskuspu/',Goods.as_view(),name='goods'),
    path("auth/login/",CustomAuthToken.as_view(),name='authtoken'),
    path("auth/signup/",RegisterView.as_view(),name='register'),
    path("auth/upimg/",UserAvatarUpdateView.as_view(),name='upimg'),
    path("auth/article/",ArticleList.as_view(),name='article'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

sh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shshop.public.sites import sh_site
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shadmin/", sh_site.urls),
    path("", include("shshop.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/", include("api.urls")),
    # 3. coreapi文档路径
    path("docs/", include_docs_urls(title="接口测试平台API文档", description="这个是接口平台的文档")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shshop/module/article/urls.py
from django.urls import path
from shshop.module.article import views

urlpatterns = [
    path("", views.ShArticleListView.as_view(), name="article_list"),
    path("<int:pk>/", views.ShArticleDetailView.as_view(), name="article_detail"),
    path('cate/<int:pk>/', views.ShArticleCategoryListView.as_view(), name='article_category_list'),
]

shshop/module/cart/urls.py
from django.urls import path
from shshop.module.cart import views

urlpatterns = [
    path("", views.ShShopingCartListView.as_view(), name="carts"),
    path("add/", views.ShShopingCartCreateView.as_view(), name="add_cart"),
    path("update/num/", views.ShShopingCartUpdateView.as_view(), name="update_cart")
]

shshop/module/goods/urls.py
from django.urls import path
from shshop.module.goods import views

urlpatterns = [
    path("", views.ShShopSPUListView.as_view(), name="spus"),
    path("cate/<int:pk>/", views.ShShopCategoryDetailView.as_view(), name="cate_detail"),
    path("search/", views.SearchTemplateView.as_view(), name="search"),
    path("spu/<int:pk>/", views.ShShopSPUDetailView.as_view(), name="spu_detail"),
]

shshop/module/post/urls.py
from django.urls import path
from shshop.module.post import views

urlpatterns = [
    # path("", views.ShShopingpostListView.as_view(), name="posts"),
    path("", views.POST, name="posts"),
    # path("add/", views.ShShopingpostCreateView.as_view(), name="add_post"),
    # path("update/num/", views.ShShopingpostUpdateView.as_view(), name="update_post")
]

shshop/module/user/urls.py
from django.urls import path
from shshop.module.user import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("add/address/",
         views.ShShopAddressCreateView.as_view(),
         name="add_address"),
    path("address/",
         views.ShShopAddressListView.as_view(),
         name="addrs_list"),
    path("userinfo/", views.UserInfoTemplateView.as_view(), name="userinfo"),
    path("balance/",
         views.ShUserBalanceLogTemplateView.as_view(),
         name="balance"),
]

shshop/urls.py
from django.urls import path, include

app_name = "shshop"

urlpatterns = [
    path("", include('shshop.public.urls')),
    path("user/", include('shshop.module.user.urls')),
    path("goods/", include('shshop.module.goods.urls')),
    path("cart/", include('shshop.module.cart.urls')),
    path("post/", include('shshop.module.post.urls')),
    path("order/", include('shshop.module.order.urls')),
    path("comments/", include('shshop.module.comments.urls')),
    path("article/", include('shshop.module.article.urls')),
	path("payment/", include('shshop.module.payment.urls')),
]

shshop/models.py
from django.db import models

# Create your models here.
from shshop.public.models import (ShMenu, ShPermission, ShBanner,
                                     ShUpload)

from shshop.module.user.models import (UserInfo, ShUserBalanceLog,
                                          ShShopAddress)

from shshop.module.goods.models import (ShShopCategory, ShShopSPU,
                                           ShShopSpec, ShShopSpecOption,
                                           ShShopSKU, ShSPUCarousel)

from shshop.module.cart.models import ShShopingCart
from shshop.module.post.models import GoodPost
from shshop.module.order.models import ShShopOrderInfo, ShShopOrderSKU
from shshop.module.comments.models import ShOrderInfoComments
from shshop.module.stats.models import ShIPAddress, ShStats
from shshop.module.article.models import ShArticleCategory, ShArticle, ShArticleTags

shshop/module/cart/forms.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm

from shshop.models import ShShopingCart

class ShShopingCartForm(ModelForm):

    class Meta:
        model = ShShopingCart
        fields = ['sku', 'num']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

shshop/module/comments/forms.py
from django import forms

from shshop.models import ShOrderInfoComments


class ShOrderInfoCommentsModelForm(forms.ModelForm):

    class Meta:
        model = ShOrderInfoComments
        fields = ('content', 'comment_choices', 'object_id')
        widgets = {
            'content': forms.Textarea(attrs={"class":"textarea","rows": 5,  "placeholder":"请如实发表您对该商品的感受..."}),
        }

shshop/module/article/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :views.py
@说明    :用户消息视图
@时间    :2023/03/24 15:04:52
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from shshop.models import ShArticle, ShArticleCategory, ShArticleTags


class ArticleContext:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cates'] = self.get_cates()
        context['tags'] = self.get_tags()
        # context['archive'] = ShArticle.get_archive()
        context['tags_classes'] = ['is-danger', 'is-info', 'is-success', 'is-primary', 'is-light', 'is-black']
        return context

    def get_cates(self):
        return ShArticleCategory.objects.all()

    def get_tags(self):
        return ShArticleTags.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

    def get_stats(self, object_id):
        return ShArticle.get_stats(self.request, object_id)


class ShArticleListView(ArticleContext, ListView):
    """ 用户消息列表 """

    model = ShArticle
    template_name = "shshop/article/article_list.html"
    paginate_by = 15


class ShArticleDetailView(ArticleContext, DetailView):
    """ 用户消息详情 """
    model = ShArticle
    template_name = "shshop/article/article_detail.html"
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.pv = self.get_stats(obj.id).pv
        obj.uv = self.get_stats(obj.id).uv
        return obj


class ShArticleCategoryListView(ArticleContext, SingleObjectMixin, ListView):
    """ 分类用户消息列表 """

    paginate_by = 15
    template_name = "shshop/article/article_list.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.get_cates())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cate'] = self.object
        return context

    def get_queryset(self):
        queryset = self.object.sharticle_set.all()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

shshop/module/cart/views.py
from django.views.generic import CreateView, ListView, View
from django.db.models import F
from django.db.utils import IntegrityError
from django.contrib import messages
from django.urls import reverse_lazy
from shshop.models import ShShopingCart, ShShopAddress
from shshop.public.mixins import (
    JsonableResponseMixin, JsonLoginRequiredMixin, JsonResponse,
    LoginRequiredMixin
)


class ShShopingCartCreateView(JsonLoginRequiredMixin, JsonableResponseMixin, CreateView):
    """ 加入购物车 """
    model = ShShopingCart
    fields = ['sku', 'num']
    success_url = reverse_lazy('shshop:carts')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        try:
            self.object = form.save()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
        except IntegrityError:
            carts = ShShopingCart.objects.filter(owner=self.request.user, sku=form.cleaned_data['sku'])
            carts.update(num=F('num')+int(form.cleaned_data['num']))
            self.object = carts.first()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
            return JsonResponse({'pk': self.object.id, 'code': 'ok', 'message': '已成功加入购物车！'}, json_dumps_params={'ensure_ascii': False})
        return super().form_valid(form)


class ShShopingCartListView(LoginRequiredMixin, ListView):

    template_name = "shshop/cart/carts.html"
    context_object_name = "carts"

    def get_queryset(self):
        queryset = ShShopingCart.objects.filter(owner=self.request.user)
        total = 0
        carts = []
        for cart in queryset:
            cart_dict = {}
            cart_dict['id'] = cart.id
            cart_dict['title'] = cart.sku.spu.title
            cart_dict['sku_id'] = cart.sku.id
            cart_dict['cover_pic'] = cart.sku.cover_pic.url
            cart_dict['options'] = list(cart.sku.options.values('name', 'spec__name'))
            cart_dict['price'] = cart.sku.price.to_eng_string()
            cart_dict['stock'] = cart.sku.stock
            cart_dict['sales'] = cart.num
            cart_dict['total_price'] = cart.num * cart.sku.price
            carts.append(cart_dict)
            total += cart.num * cart.sku.price
        return carts


class ShShopingCartUpdateView(JsonLoginRequiredMixin, View):
    """ 修改购物车数量 """

    def post(self, request, *args, **kwargs):
        cleaned_data = request.POST
        carts = ShShopingCart.objects.filter(owner=self.request.user, id=int(cleaned_data['id']))
        # 修改
        if carts.exists() and cleaned_data.get('actions') == 'update':
            carts.update(num=int(cleaned_data['num']))
            return JsonResponse({'code':'ok', 'message': '修改成功！'})
        # 删除
        elif carts.exists() and cleaned_data.get('actions') == 'delete':
            carts.delete()
            return JsonResponse({'code':'ok', 'message': '删除成功！'})
        else:
            return JsonResponse({'code':'err', 'message': '该购物不存在！'})

shshop/module/comments/views.py
from django.contrib.contenttypes.models import ContentType
from django.http.response import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages

from shshop.models import ShShopSKU, ShShopOrderSKU
from shshop.templatetags.shop_tags import commented_func
from shshop.module.order.views import ShShopOrderInfoDetailView
from shshop.module.comments.forms import ShOrderInfoCommentsModelForm


class ShOrderInfoCommentsFormView(ShShopOrderInfoDetailView):

    template_name = "shshop/comments/comments_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ShOrderInfoCommentsModelForm()
        return context

    def post(self, request, *args, **kwargs):

        # 判断评论时机
        if self.get_object().pay_status != 4:
            raise Http404

        form = ShOrderInfoCommentsModelForm(request.POST)
        content_type = ContentType.objects.get_for_model(ShShopSKU)
        form.instance.content_type = content_type
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            # 修改评论标志
            oskus = ShShopOrderSKU.objects.filter(
                    order=self.get_object(), sku__id=form.cleaned_data['object_id']
                )
            oskus.update(is_commented=True)
            # 修改订单状态
            if commented_func(self.get_object()):
                obj = self.get_object()
                obj.pay_status = 5
                obj.save()
            messages.add_message(request, messages.SUCCESS, f'评价发表成功！')
        return HttpResponseRedirect(f'{reverse("shshop:spu_detail", args=[oskus.first().sku.spu.id])}?tabsActive=comment')

shshop/module/order/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib import messages


from shshop.config.settings import sh_settings
from shshop.public.mixins import LoginRequiredMixin
from shshop.models import ShShopOrderInfo


class ShshopOrderInfoListView(LoginRequiredMixin, ListView):
    """ 订单列表 """
    model = ShShopOrderInfo
    template_name = "shshop/order/order_list.html"
    context_object_name = "order_list"
    paginate_by = sh_settings.USER_ORDERINFO_PAGINATE_BY
    paginate_orphans = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.request.GET.get('status') if self.request.GET.get('status') else ''
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-add_date').filter(owner=self.request.user)
        cleaned_data = self.request.GET.dict()
        if cleaned_data and (cleaned_data.get('status') in ['1', '2', '3', '4', '5', '6']):
            queryset = queryset.filter(pay_status=int(cleaned_data['status']))
        return queryset

    def post(self, request, *args, **kwargs):
        orders = ShShopOrderInfo.objects.filter(owner=request.user, order_sn=request.POST['order_sn'])
        orders.update(pay_status=4)
        messages.add_message(request, messages.SUCCESS, f'订单{orders.first()}已确认收货！')
        return HttpResponseRedirect(f"{request.path}?status=4")


class ShShopOrderInfoDetailView(LoginRequiredMixin, DetailView):
    """ 订单结算支付 """

    model = ShShopOrderInfo
    template_name = "shshop/order/order_detail.html"
    context_object_name = "order"
    slug_field="order_sn"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_methods'] = self.get_pay_methods()
        return context

    def get_pay_methods(self):
        pay_methods = ShShopOrderInfo.get_pay_method()
        pay_list = [
            {
                'value': 1,
                'name': pay_methods[1],
                'icon': "/static/shshop/img/hdpay.svg",
                'is_default': False,
            },
            {
                'value': 4,
                'name': pay_methods[4],
                'icon': "/static/shshop/img/ye.svg",
                'is_default': False,
            }
        ]
        return pay_list


class ShShopOrderInfoUserDetailView(ShShopOrderInfoDetailView):

    template_name = "shshop/order/user_order_detail.html"

shshop/templates/shshop/banner.html
{{ carousels|json_script:"carousel-data" }}
<div id="carousel" class="container">
    <template>
        <b-carousel>
            <b-carousel-item v-for="(carousel, i) in carousels" :key="i">
                <section :class="`hero is-medium`">
                    <a class="image" :href="carousel.target_url">
                        <img width="100%" :src="`${carousel.img}`" :alt="carousel.desc"> 
                    </a>
                </section>
            </b-carousel-item>
        </b-carousel>
    </template>
</div>
<script>
    var value = JSON.parse(document.getElementById('carousel-data').textContent);
    var carousel = new Vue({
        el: '#carousel',
        delimiters: ['{$', '$}'],
        data: {
            carousels: value
        }
    })
</script>

shshop/templates/shshop/base.html
{% load i18n static shop_tags %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:" en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}-SHShop</title>
    <link rel="stylesheet" href="{% block stylesheet %}{% static "shshop/css/buefy.min.css" %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'shshop/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.min.css">
    <script src="{% static 'shshop/js/vue.js' %}"></script>
    <script src="{% static 'shshop/js/buefy.min.js' %}"></script>
    {% block extrastyle %}{% endblock %}
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}" data-admin-utc-offset="{% now " Z"
    %}">

    <div id="header">
        {% block header %}
        {% if '/article/' in request.get_full_path or '/goods/' in request.get_full_path %}

        {% else %}
        <div id="header-top" class="has-background-black-bis">
            <div class="is-flex is-justify-content-space-between is-align-items-center container" style="height:40px">
                <div class="head-top-left">
                    {% block head_top_left %}
                    欢迎您光临本店！
                    {% endblock %}
                </div>
                <div class="head-top-right">
                    {% block head_top_right %}
                    {% if request.user.is_authenticated %}
                    <div class="dropdown is-hoverable usertools">
                        <div class="dropdown-trigger">
                            <button class="button is-radiusless is-shadowless" aria-haspopup="true"
                                aria-controls="dropdown-menu4" style="background: none; border:none">
                                <span>欢迎您，{{ request.user.username }}</span>
                                <span class="icon is-small">
                                    <i class="mdi mdi-menu-down" aria-hidden="true"></i>
                                </span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu4" role="menu" style="z-index:1000">
                            <div class="dropdown-content">
                                <a class="dropdown-item" href="{% url 'shshop:userinfo' %}">
                                    <span class="mdi mdi-account-box-outline"></span>
                                    个人中心
                                </a>
                                <a class="dropdown-item" href="{% url 'shshop:order_list' %}">
                                    <span class="mdi mdi-basket-plus-outline"></span>
                                    我的订单
                                </a>
                                <div class=" dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'shshop:logout' %}">
                                    <span class="mdi mdi-logout"></span>
                                    退出
                                </a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <a class="mr-2" href="{% url 'shshop:login' %}" target="_top">
                        <span class="icon"><i class="mdi mdi-login"></i></span>
                        登录
                    </a> <span class="is-size-6">|</span>
                    <a class="mr-3" href="{% url 'shshop:register' %}" target="_top">
                        <span class="icon"><i class="mdi mdi-cash-register"></i></span>
                        注册
                    </a>
                    {% endif %}
                    <a class="post" href="{% url 'shadmin:login' %}" >
                        <span class="icon"><i class="mdi mdi-account"></i></span>
                       发布用户消息与管理
                    </a>
                    <a class="cart" href="{% url 'shshop:posts' %}" >
                        <span class="icon"><i class="mdi mdi-upload"></i></span>
                       发布商品
                    </a>
                    <a class="cart" href="{% url 'shshop:carts' %}" id="cartNum">
                        <span class="icon"><i class="mdi mdi-cart-check"></i></span>
                        购物车({$ cart_num $})
                    </a>
                    {% endblock %}
                </div>
            </div>
        </div>
        {% endif %}
        <div id="header">
            <div id="navbar">
                <template>
                    <b-navbar spaced shadow1 transparent wrapper-class="{% block navclass %}container{% endblock %}">
                        <template #brand>
                            <b-navbar-item tag="div">
                                {% block navbar_logo %}
                                <h1 class="is-size-4 has-text-weight-medium">SH</h1>
                                {% endblock %}
                            </b-navbar-item>
                        </template>
                        <template #start>
                            {% block navbar_start %}
                            <b-navbar-item href="{% url 'shshop:home' %}">
                                首页
                            </b-navbar-item>
                            <b-navbar-item href="{% url 'shshop:spus' %}">
                                全部分类
                            </b-navbar-item>
                            <b-navbar-item href="{% url 'shshop:article_list' %}">
                                用户消息
                            </b-navbar-item>
                            {% navbar_result as cates %}
                            {% for cate in cates %}
                            <b-navbar-dropdown label="{{ cate.name }}">
                                {% for sub_cate in cate.sub_cates %}
                                <b-navbar-item href="{% url 'shshop:cate_detail' sub_cate.id %}">
                                    {{ sub_cate.name }}
                                </b-navbar-item>
                                {% endfor %}
                            </b-navbar-dropdown>
                            {% endfor %}
                            {% endblock %}
                        </template>

                        <template #end>
                            {% block navbar_end %}
                            <b-navbar-item tag="div">
                                <form action="{% url 'shshop:search' %}" method="get">
                                    {% csrf_token %}
                                    {% search request %}
                                </form>
                            </b-navbar-item>
                            {% endblock %}
                        </template>
                    </b-navbar>
                </template>
            </div>
        </div>
        {% endblock %}
    </div>

    <div id="main">
        {% block breadcrumb %}
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
                <li><a href="#">Bulma</a></li>
                <li><a href="#">Documentation</a></li>
                <li><a href="#">Components</a></li>
                <li class="is-active"><a href="#" aria-current="page">Breadcrumb</a></li>
            </ul>
        </nav>
        {% endblock %}
        {% block content %}{% endblock %}
    </div>
    {% if '/' == request.get_full_path %}
    {% include 'shshop/footer.html' %}
    {% else %}

    {% endif %}

    {% if messages %}
    {% for message in messages %}
    <div id="notification">
        <b-notification auto-close {% if message.tags %}type="is-{{ message.tags }} is-light" {% endif %}
            :duration="3000" has-icon position="is-top-right" aria-close-label="Close notification">
            {{ message }}
        </b-notification>
    </div>
    {% endfor %}
    <script>
        var notification = new Vue({
            el: '#notification',
            delimiters: ['{$', '$}'],
        })
    </script>
    {% endif %}

    <script>
        var navbar = new Vue({
            el: '#navbar',
            delimiters: ['{$', '$}'],
            data: {},
            methods: {
                toastMessage(type, message) {
                    return this.$buefy.toast.open({
                        message: message,
                        type: type
                    })
                },
            }
        })
    </script>
    <script>
        var cartNum = new Vue({
            el: '#cartNum',
            delimiters: ['{$', '$}'],
            data: {
                cart_num: '{% cart_num request.user %}'
            }
        })
    </script>

    {% block extra_script %}{% endblock %}
    {% block vue %}{% endblock %}
</body>

</html>

shshop/templates/shshop/base_site.html
{% extends 'shshop/base.html' %}

{% block title %}校园二手市场{% endblock %}

{% block breadcrumb %}{% endblock %}

shshop/templates/shshop/index.html
{% extends 'shshop/base_site.html' %}

{% load i18n shop_tags %}

{% block content %}
<div class=" has-background-white">
    {% banners_result %}
</div>
    <div class="container mt-4 mb-4">
        {% for cate in cates %}
        <div class="is-flex is-align-items-center is-justify-content-space-between mb-2">
            <div class="">
                <h1 class=" has-text-weight-semibold is-size-5">{{ cate.name }}</h1>
            </div>
            <div class="">
                <a href="{% url 'shshop:cate_detail' cate.id %}">更多>></a>
            </div>
        </div>
        <div class="columns is-multiline is-mobile">
            <div class="column is-4-fullhd is-6-tablet is-12-mobile">
                <figure class="image is-4by3">
                    <img src="{% if cate.img_map %} {{ cate.img_map.url }}{% endif %}" alt="" srcset="">
                </figure>
            </div>
            {% for spu in cate.spus %}
            <div class="column is-2-fullhd is-3-tablet is-6-mobile">
                <div class="is-flex is-flex-direction-column is-justify-content-space-between has-background-white" style="height:100%">
                    {% spu_box spu %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
{% endblock %}

shshop/templates/shshop/page.html
{% if page_obj %}
<nav class="pagination is-centered1 is-small" role="navigation" aria-label="pagination">
    {% if page_obj.has_previous %}
        <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}{{ params }}">{{ pre_name }}</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a class="pagination-next" href="?page={{ page_obj.next_page_number }}{{ params }}">{{ next_name }}</a>
    {% endif %}
    <ul class="pagination-list">
        {% for p in page_obj.paginator.get_elided_page_range %}
        {% if p != '...' %}
        <li>
            <a href="?page={{ p }}{{ params }}"
                class="pagination-link {% if page_obj.number == p %} is-current {% endif %}" 
                    {% if page_obj.number == p %}aria-current="page" {% endif %} aria-label="Goto page {{ p }}">
            {{ p }}
            </a>
        </li>
        {% else %}
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endif %}