sh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shshop.public.sites import sh_site
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shadmin/", sh_site.urls),
    path("", include("shshop.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/", include("api.urls")),
    # 3. coreapi文档路径
    path("docs/", include_docs_urls(title="接口测试平台API文档", description="这个是接口平台的文档")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shshop/module/cart/urls.py
from django.urls import path
from shshop.module.cart import views

urlpatterns = [
    path("", views.ShShopingCartListView.as_view(), name="carts"),
    path("add/", views.ShShopingCartCreateView.as_view(), name="add_cart"),
    path("update/num/", views.ShShopingCartUpdateView.as_view(), name="update_cart")
]

shshop/module/comments/urls.py
from django.urls import path
from shshop.module.comments import views


urlpatterns = [
    path("<int:slug>/form/", views.ShOrderInfoCommentsFormView.as_view(), name="comments_create")
]

shshop/module/order/urls.py
from django.urls import path
from shshop.module.order import views

urlpatterns = [
    path("list/", views.ShshopOrderInfoListView.as_view(), name="order_list"),
    path("<int:slug>/", views.ShShopOrderInfoDetailView.as_view(), name="order_detail"),
    path("detail/<int:slug>/", views.ShShopOrderInfoUserDetailView.as_view(), name="user_order_detail")
]

shshop/module/payment/urls.py
from django.urls import path
from shshop.module.payment import views


urlpatterns = [
    path("", views.CashRegisterTemplateView.as_view(), name="cash_register"),
    path("paynow/", views.PayNowView.as_view(), name="pay_now"),

]

shshop/module/post/urls.py
from django.urls import path
from shshop.module.post import views

urlpatterns = [
    # path("", views.ShShopingpostListView.as_view(), name="posts"),
    path("", views.POST, name="posts"),
    # path("add/", views.ShShopingpostCreateView.as_view(), name="add_post"),
    # path("update/num/", views.ShShopingpostUpdateView.as_view(), name="update_post")
]

shshop/urls.py
from django.urls import path, include

app_name = "shshop"

urlpatterns = [
    path("", include('shshop.public.urls')),
    path("user/", include('shshop.module.user.urls')),
    path("goods/", include('shshop.module.goods.urls')),
    path("cart/", include('shshop.module.cart.urls')),
    path("post/", include('shshop.module.post.urls')),
    path("order/", include('shshop.module.order.urls')),
    path("comments/", include('shshop.module.comments.urls')),
    path("article/", include('shshop.module.article.urls')),
	path("payment/", include('shshop.module.payment.urls')),
]

shshop/module/order/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-


from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from shshop.public.abstract import AbstractModel
from shshop.models import ShShopSKU

User = get_user_model()


class ShShopOrderInfo(AbstractModel):
    """订单信息"""

    class PayMethodChoices(models.IntegerChoices):
        CASH = 1, _('货到付款')
        ALIPAY = 2, _('支付宝')
        WECHATPAY = 3, _('微信支付')
        OVERPAY = 4, _('余额支付')

    class OrderStatusChoices(models.IntegerChoices):
        TOBPAY = 1, _('待支付')
        TOBDELIVER = 2, _('待发货')
        TOBRECEIVED = 3, _('待收货')
        TOBEVALUATE = 4, _('待评价')
        COMPLETE = 5, _('已完成')
        CANCELLED = 6, _('已取消')

    owner = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name="用户",
        editable=False
    )
    order_sn = models.CharField(
        blank=True,
        default="",
        unique=True,
        max_length=32,
        editable=False,
        verbose_name="订单号",
        help_text="订单号"
    )
    trade_sn = models.CharField(
        blank=True, null=True,
        unique=True, max_length=64,
        verbose_name="交易号",
        help_text="交易号",
        editable=False
    )
    pay_status = models.IntegerField(
        choices=OrderStatusChoices.choices,
        default=1,
        verbose_name="支付状态",
        help_text="支付状态"
    )
    pay_method = models.IntegerField(
        choices=PayMethodChoices.choices,
        verbose_name="支付方式",
        help_text="支付方式",
        blank=True,
        null=True,
        editable=False
    )
    total_amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name="商品总金额"
    )
    order_mark = models.CharField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="订单备注",
        help_text="订单备注"
    )
    name = models.CharField("签收人", max_length=50, default="")
    phone = models.CharField("手机号", max_length=11, default="")
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    address = models.CharField("地址", max_length=200)
    pay_time = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="支付时间",
        help_text="支付时间",
        editable=False
    )

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn

    @classmethod
    def get_pay_method(cls):
        # 支付方式列表字典
        return dict(cls.PayMethodChoices.choices)

    @classmethod
    def get_pay_default(cls):
        # 获取支付方式的默认值
        return cls._meta.get_field('pay_method').default


class ShShopOrderSKU(AbstractModel):
    """订单商品"""
    order = models.ForeignKey(
        ShShopOrderInfo,
        on_delete=models.CASCADE,
        verbose_name="订单",
        editable=False
    )
    sku = models.ForeignKey(
        ShShopSKU,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        verbose_name="订单商品",
        editable=False
    )
    title = models.CharField("商品标题", max_length=200, blank=True, default="")
    desc = models.CharField("商品说明", max_length=200, blank=True, default="")
    spec = models.CharField("发布区域", max_length=200, blank=True, default="")
    content = models.TextField("商品详情", blank=True, default="")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField('单价', max_digits=18, decimal_places=2)
    is_commented = models.BooleanField(default=False, verbose_name="是否已评价")

    class Meta:
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

    def __str__(self) -> str:
        return self.sku.spu.title

shshop/module/cart/forms.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm

from shshop.models import ShShopingCart

class ShShopingCartForm(ModelForm):

    class Meta:
        model = ShShopingCart
        fields = ['sku', 'num']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

shshop/module/comments/forms.py
from django import forms

from shshop.models import ShOrderInfoComments


class ShOrderInfoCommentsModelForm(forms.ModelForm):

    class Meta:
        model = ShOrderInfoComments
        fields = ('content', 'comment_choices', 'object_id')
        widgets = {
            'content': forms.Textarea(attrs={"class":"textarea","rows": 5,  "placeholder":"请如实发表您对该商品的感受..."}),
        }

shshop/module/article/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :views.py
@说明    :用户消息视图
@时间    :2023/03/24 15:04:52
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from shshop.models import ShArticle, ShArticleCategory, ShArticleTags


class ArticleContext:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cates'] = self.get_cates()
        context['tags'] = self.get_tags()
        # context['archive'] = ShArticle.get_archive()
        context['tags_classes'] = ['is-danger', 'is-info', 'is-success', 'is-primary', 'is-light', 'is-black']
        return context

    def get_cates(self):
        return ShArticleCategory.objects.all()

    def get_tags(self):
        return ShArticleTags.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

    def get_stats(self, object_id):
        return ShArticle.get_stats(self.request, object_id)


class ShArticleListView(ArticleContext, ListView):
    """ 用户消息列表 """

    model = ShArticle
    template_name = "shshop/article/article_list.html"
    paginate_by = 15


class ShArticleDetailView(ArticleContext, DetailView):
    """ 用户消息详情 """
    model = ShArticle
    template_name = "shshop/article/article_detail.html"
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.pv = self.get_stats(obj.id).pv
        obj.uv = self.get_stats(obj.id).uv
        return obj


class ShArticleCategoryListView(ArticleContext, SingleObjectMixin, ListView):
    """ 分类用户消息列表 """

    paginate_by = 15
    template_name = "shshop/article/article_list.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.get_cates())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cate'] = self.object
        return context

    def get_queryset(self):
        queryset = self.object.sharticle_set.all()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

shshop/module/cart/views.py
from django.views.generic import CreateView, ListView, View
from django.db.models import F
from django.db.utils import IntegrityError
from django.contrib import messages
from django.urls import reverse_lazy
from shshop.models import ShShopingCart, ShShopAddress
from shshop.public.mixins import (
    JsonableResponseMixin, JsonLoginRequiredMixin, JsonResponse,
    LoginRequiredMixin
)


class ShShopingCartCreateView(JsonLoginRequiredMixin, JsonableResponseMixin, CreateView):
    """ 加入购物车 """
    model = ShShopingCart
    fields = ['sku', 'num']
    success_url = reverse_lazy('shshop:carts')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        try:
            self.object = form.save()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
        except IntegrityError:
            carts = ShShopingCart.objects.filter(owner=self.request.user, sku=form.cleaned_data['sku'])
            carts.update(num=F('num')+int(form.cleaned_data['num']))
            self.object = carts.first()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
            return JsonResponse({'pk': self.object.id, 'code': 'ok', 'message': '已成功加入购物车！'}, json_dumps_params={'ensure_ascii': False})
        return super().form_valid(form)


class ShShopingCartListView(LoginRequiredMixin, ListView):

    template_name = "shshop/cart/carts.html"
    context_object_name = "carts"

    def get_queryset(self):
        queryset = ShShopingCart.objects.filter(owner=self.request.user)
        total = 0
        carts = []
        for cart in queryset:
            cart_dict = {}
            cart_dict['id'] = cart.id
            cart_dict['title'] = cart.sku.spu.title
            cart_dict['sku_id'] = cart.sku.id
            cart_dict['cover_pic'] = cart.sku.cover_pic.url
            cart_dict['options'] = list(cart.sku.options.values('name', 'spec__name'))
            cart_dict['price'] = cart.sku.price.to_eng_string()
            cart_dict['stock'] = cart.sku.stock
            cart_dict['sales'] = cart.num
            cart_dict['total_price'] = cart.num * cart.sku.price
            carts.append(cart_dict)
            total += cart.num * cart.sku.price
        return carts


class ShShopingCartUpdateView(JsonLoginRequiredMixin, View):
    """ 修改购物车数量 """

    def post(self, request, *args, **kwargs):
        cleaned_data = request.POST
        carts = ShShopingCart.objects.filter(owner=self.request.user, id=int(cleaned_data['id']))
        # 修改
        if carts.exists() and cleaned_data.get('actions') == 'update':
            carts.update(num=int(cleaned_data['num']))
            return JsonResponse({'code':'ok', 'message': '修改成功！'})
        # 删除
        elif carts.exists() and cleaned_data.get('actions') == 'delete':
            carts.delete()
            return JsonResponse({'code':'ok', 'message': '删除成功！'})
        else:
            return JsonResponse({'code':'err', 'message': '该购物不存在！'})

shshop/module/comments/views.py
from django.contrib.contenttypes.models import ContentType
from django.http.response import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages

from shshop.models import ShShopSKU, ShShopOrderSKU
from shshop.templatetags.shop_tags import commented_func
from shshop.module.order.views import ShShopOrderInfoDetailView
from shshop.module.comments.forms import ShOrderInfoCommentsModelForm


class ShOrderInfoCommentsFormView(ShShopOrderInfoDetailView):

    template_name = "shshop/comments/comments_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ShOrderInfoCommentsModelForm()
        return context

    def post(self, request, *args, **kwargs):

        # 判断评论时机
        if self.get_object().pay_status != 4:
            raise Http404

        form = ShOrderInfoCommentsModelForm(request.POST)
        content_type = ContentType.objects.get_for_model(ShShopSKU)
        form.instance.content_type = content_type
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            # 修改评论标志
            oskus = ShShopOrderSKU.objects.filter(
                    order=self.get_object(), sku__id=form.cleaned_data['object_id']
                )
            oskus.update(is_commented=True)
            # 修改订单状态
            if commented_func(self.get_object()):
                obj = self.get_object()
                obj.pay_status = 5
                obj.save()
            messages.add_message(request, messages.SUCCESS, f'评价发表成功！')
        return HttpResponseRedirect(f'{reverse("shshop:spu_detail", args=[oskus.first().sku.spu.id])}?tabsActive=comment')

shshop/module/order/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib import messages


from shshop.config.settings import sh_settings
from shshop.public.mixins import LoginRequiredMixin
from shshop.models import ShShopOrderInfo


class ShshopOrderInfoListView(LoginRequiredMixin, ListView):
    """ 订单列表 """
    model = ShShopOrderInfo
    template_name = "shshop/order/order_list.html"
    context_object_name = "order_list"
    paginate_by = sh_settings.USER_ORDERINFO_PAGINATE_BY
    paginate_orphans = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.request.GET.get('status') if self.request.GET.get('status') else ''
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-add_date').filter(owner=self.request.user)
        cleaned_data = self.request.GET.dict()
        if cleaned_data and (cleaned_data.get('status') in ['1', '2', '3', '4', '5', '6']):
            queryset = queryset.filter(pay_status=int(cleaned_data['status']))
        return queryset

    def post(self, request, *args, **kwargs):
        orders = ShShopOrderInfo.objects.filter(owner=request.user, order_sn=request.POST['order_sn'])
        orders.update(pay_status=4)
        messages.add_message(request, messages.SUCCESS, f'订单{orders.first()}已确认收货！')
        return HttpResponseRedirect(f"{request.path}?status=4")


class ShShopOrderInfoDetailView(LoginRequiredMixin, DetailView):
    """ 订单结算支付 """

    model = ShShopOrderInfo
    template_name = "shshop/order/order_detail.html"
    context_object_name = "order"
    slug_field="order_sn"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_methods'] = self.get_pay_methods()
        return context

    def get_pay_methods(self):
        pay_methods = ShShopOrderInfo.get_pay_method()
        pay_list = [
            {
                'value': 1,
                'name': pay_methods[1],
                'icon': "/static/shshop/img/hdpay.svg",
                'is_default': False,
            },
            {
                'value': 4,
                'name': pay_methods[4],
                'icon': "/static/shshop/img/ye.svg",
                'is_default': False,
            }
        ]
        return pay_list


class ShShopOrderInfoUserDetailView(ShShopOrderInfoDetailView):

    template_name = "shshop/order/user_order_detail.html"

shshop/templates/shshop/order/order_list.html
{% extends 'shshop/user/userinfo.html' %}

{% load shop_tags %}

{% block title %}我的订单{% endblock %}

{% block userinfo_content %}
    <div class="box is-radiusless mb-3">
        <h1 class="is-size-4">我的订单</h1>
        <div class="dropdown-divider"></div>

        <div class="tabs is-boxed is-fullwidth">
            <ul>
                <li class="{% if 'status' not in request.get_full_path or status == '' %} is-active {% endif %}" ><a href="{% url 'shshop:order_list' %}">全部订单</a></li>
                <li class="{% if 'status=1' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shshop:order_list' %}?status=1">待支付</a></li>
                <li class="{% if 'status=2' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shshop:order_list' %}?status=2">待发货</a></li>
                <li class="{% if 'status=3' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shshop:order_list' %}?status=3">待收货</a></li>
                <li class="{% if 'status=4' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shshop:order_list' %}?status=4">待评价</a></li>
                <li class="{% if 'status=5' in request.get_full_path %} is-active {% endif %}"><a href="{% url 'shshop:order_list' %}?status=5">已完成</a></li>
            </ul>
        </div>

        {% for order in page_obj %}
        <div class="box has-background-light is-shadowless">
        <div class="is-flex is-justify-content-space-between">
            <div class=" has-text-grey-light1">订单日期：{{ order.add_date }}</div>
            <div class=" has-text-danger-dark">
                {{ order.get_pay_status_display }}
            </div>
        </div>
        <div class="dropdown-divider"></div>
        {% for osku in order.shshopordersku_set.all %}
        <div class="is-flex is-justify-content-space-between">
            <div>
                <figure class=" image is-128x128">
                    <img src="{{ osku.sku.cover_pic.url }}" alt="{{ osku.title }}" srcset="">
                </figure>
            </div>
            <div class="has-background-danger1 is-flex is-flex-direction-column is-justify-content-center is-flex-grow-1 pl-3 pr-3">
                <h1 class="has-text-weight-bold">{{ osku.title }}</h1>
                {% if osku.spec %}<p class="has-text-grey-light">{{ osku.spec }}</p>{% endif %}
            </div>
            <div class="has-background-danger1 is-flex is-justify-content-center is-align-items-center">
                <p class="has-text-danger-dark">¥ {{ osku.price }} x {{ osku.count }}</p>
            </div>
        </div>
        <div class=" dropdown-divider"></div>
        {% endfor %}

        <div class="">
            {% is_order_commented order as is_commented %}
            <p class=" has-text-weight-bold pt-1 pb-1 has-text-right">共{% order_num order.shshopordersku_set.all %}件商品，总金额{{ order.total_amount }}元（含运费）</p>
            <div class=" buttons is-justify-content-end">
                {% if order.pay_status == 1 %}
                    <a class="button is-primary is-small" href="{% url 'shshop:order_detail' order.order_sn %}">立即支付</a>
                {% elif order.pay_status == 3 %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="order_sn" value="{{ order.order_sn }}">
                        <button class="button is-primary is-small" type="submit">确认收货</button>
                    </form>
                {% elif order.pay_status == 4 and not is_commented %}
                    <a class=" button is-primary is-small" href="{% url 'shshop:comments_create' order.order_sn %}">立即评价</a>
                {% endif %}
                <a href="{% url 'shshop:user_order_detail' order.order_sn %}" class="button is-small">订单详情</a>
            </div>
        </div>

        </div>
        {% empty %}
        <p class=" has-text-danger has-text-centered pt-6 pb-6">还没有相关订单信息哦！</p>
        {% endfor %}

        {% if page_obj %}
        <nav class="pagination is-centered1 is-small" role="navigation" aria-label="pagination">
            {% if page_obj.has_previous %}
            <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}&status={{ status }}">Previous</a>
            {% endif %}
            {% if page_obj.has_next %}
            <a class="pagination-next" href="?page={{ page_obj.next_page_number }}&status={{ status }}">Next page</a>
            {% endif %}
            <ul class="pagination-list">
                {% for p in page_obj.paginator.get_elided_page_range %}
                    {% if p != '...' %}
                    <li><a href="?page={{ p }}&status={{ status }}" class="pagination-link {% if page_obj.number == p %} is-current {% endif %}" {% if page_obj.number == p %}aria-current="page"{% endif %} aria-label="Goto page {{ p }}">{{ p }}</a></li>
                    {% else %}
                    <li><span class="pagination-ellipsis">&hellip;</span></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
        {% endif %}
    </div>
{% endblock %}

shshop/templates/shshop/order/user_order_detail.html
{% extends 'shshop/user/userinfo.html' %}

{% load shop_tags %}

{% block title %} 订单详情 {% endblock %}


{% block extrastyle %}
    <!-- <style>.b-steps .steps+.step-content{padding: 0 !important;}</style> -->
{% endblock extrastyle %}

{% block userinfo_content %}

{% block orderinfo %}
    <div class="box is-radiusless is-marginless pt-6" id="orderStatus">
        <b-steps v-model="activeStep" :has-navigation="false">
            <b-step-item label="待付款" icon="account-key" :clickable="false"></b-step-item>
            <b-step-item label="待发货" icon="car" :clickable="false"></b-step-item>
            <b-step-item label="待收货" icon="account-plus" :clickable="false"></b-step-item>
            <b-step-item label="待评价" icon="comment-plus" :clickable="false"></b-step-item>
            <b-step-item label="已完成" icon="store" :clickable="false"></b-step-item>
        </b-steps>
    </div>

    <div class="box is-radiusless is-marginless">
        <h1 class=" is-size-5">订单信息</h1>
        <div class="dropdown-divider"></div>
        <ul style="line-height: 30px;">
            <li>订单编号：{{ order.order_sn }}</li>

            <li>订单日期：{{ order.add_date }}</li>

            <li>支付状态：{{ order.get_pay_status_display }}</li>

            {% if order.pay_status > 1 and order.pay_status != 6 %}
            <li>支付方式：{{ order.get_pay_method_display }}</li>
            {% endif %}

            <li>订单金额：¥{{ order.total_amount }}</li>

            <li>订单留言：{{ order.order_mark }}</li>
        </ul>
    </div>

    <div class="box is-radiusless is-marginless1">
        <h1 class=" is-size-5">收货信息</h1>
        <div class="dropdown-divider"></div>
        <ul style="line-height: 30px;">
            <li>签收人：{{ order.name }}</li>

            <li>手机号：{{ order.phone }}</li>

            <li>收货地址：{{ order.address }}</li>
        </ul>
    </div>
{% endblock %}
    <div class="box is-radiusless mb-4">
        <h1 class=" is-size-5">商品信息</h1>
        <div class="dropdown-divider"></div>
        {% for osku in order.shshopordersku_set.all %}
        <div class="is-flex is-justify-content-space-between">
            <div>
                <figure class=" image is-128x128">
                    <img src="{{ osku.sku.cover_pic.url }}" alt="{{ osku.title }}" srcset="">
                </figure>
            </div>
            <div class="has-background-danger1 is-flex is-flex-direction-column is-justify-content-center is-flex-grow-1 pl-3 pr-3">
                <h1 class="has-text-weight-bold">{{ osku.title }}</h1>
                {% if osku.spec %}<p class="has-text-grey-light">{{ osku.spec }}</p>{% endif %}
            </div>
            <div class=" has-background-danger1 is-flex is-justify-content-center is-align-items-center">
                <p class=" has-text-danger-dark">¥ {{ osku.price }} x {{ osku.count }}</p>
            </div>
        </div>
        <div class=" dropdown-divider"></div>

        {% if not osku.is_commented %}
            {% block order_comment %}{% endblock %}
        {% endif %}

        {% endfor %}

        {% block order_actions %}
        <div class="">
            <p class="has-text-weight-bold pt-1 pb-1 has-text-right">共{% order_num order.shshopordersku_set.all %}件商品，总金额{{ order.total_amount }}元（含运费）</p>
            {% is_order_commented order as is_commented %}
            <div class="buttons is-justify-content-end">
                {% if order.pay_status == 1 %}
                    <a class="button is-primary is-small" href="{% url 'shshop:order_detail' order.order_sn %}">立即支付</a>
                {% elif order.pay_status == 3 %}
                <form action="{% url 'shshop:order_list' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="order_sn" value="{{ order.order_sn }}">
                    <button class="button is-primary is-small" type="submit">确认收货</button>
                </form>
                {% elif order.pay_status == 4 and not is_commented %}
                <a class=" button is-primary is-small" href="{% url 'shshop:comments_create' order.order_sn %}">立即评价</a>
                {% endif %}
            </div>

        </div>
        {% endblock %}

    </div>

{% endblock %}


{% block vue %}
    <script>
        var orderStatus = new Vue({
            el: '#orderStatus',
            delimiters: ['{$', '$}'],
            data:{
                activeStep: 0,
            },
            created(){
                this.orderStatusMethod()
            },
            methods:{
                orderStatusMethod() {
                    switch (Number('{{ order.pay_status }}')) {
                        case 1:
                            this.activeStep = 0;
                            break;
                        case 2:
                            this.activeStep = 1;
                            break;
                        case 3:
                            this.activeStep = 2;
                            break;
                        case 4:
                            this.activeStep = 3;
                            break;
                        case 5:
                            this.activeStep = 4;
                            break;
                    }
                },
            }
        })
    </script>
{% endblock %}