sh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shshop.public.sites import sh_site
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shadmin/", sh_site.urls),
    path("", include("shshop.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/", include("api.urls")),
    # 3. coreapi文档路径
    path("docs/", include_docs_urls(title="接口测试平台API文档", description="这个是接口平台的文档")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shshop/module/cart/urls.py
from django.urls import path
from shshop.module.cart import views

urlpatterns = [
    path("", views.ShShopingCartListView.as_view(), name="carts"),
    path("add/", views.ShShopingCartCreateView.as_view(), name="add_cart"),
    path("update/num/", views.ShShopingCartUpdateView.as_view(), name="update_cart")
]

shshop/module/order/urls.py
from django.urls import path
from shshop.module.order import views

urlpatterns = [
    path("list/", views.ShshopOrderInfoListView.as_view(), name="order_list"),
    path("<int:slug>/", views.ShShopOrderInfoDetailView.as_view(), name="order_detail"),
    path("detail/<int:slug>/", views.ShShopOrderInfoUserDetailView.as_view(), name="user_order_detail")
]

shshop/module/payment/urls.py
from django.urls import path
from shshop.module.payment import views


urlpatterns = [
    path("", views.CashRegisterTemplateView.as_view(), name="cash_register"),
    path("paynow/", views.PayNowView.as_view(), name="pay_now"),

]

shshop/module/post/urls.py
from django.urls import path
from shshop.module.post import views

urlpatterns = [
    # path("", views.ShShopingpostListView.as_view(), name="posts"),
    path("", views.POST, name="posts"),
    # path("add/", views.ShShopingpostCreateView.as_view(), name="add_post"),
    # path("update/num/", views.ShShopingpostUpdateView.as_view(), name="update_post")
]

shshop/urls.py
from django.urls import path, include

app_name = "shshop"

urlpatterns = [
    path("", include('shshop.public.urls')),
    path("user/", include('shshop.module.user.urls')),
    path("goods/", include('shshop.module.goods.urls')),
    path("cart/", include('shshop.module.cart.urls')),
    path("post/", include('shshop.module.post.urls')),
    path("order/", include('shshop.module.order.urls')),
    path("comments/", include('shshop.module.comments.urls')),
    path("article/", include('shshop.module.article.urls')),
	path("payment/", include('shshop.module.payment.urls')),
]

shshop/module/order/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-


from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from shshop.public.abstract import AbstractModel
from shshop.models import ShShopSKU

User = get_user_model()


class ShShopOrderInfo(AbstractModel):
    """订单信息"""

    class PayMethodChoices(models.IntegerChoices):
        CASH = 1, _('货到付款')
        ALIPAY = 2, _('支付宝')
        WECHATPAY = 3, _('微信支付')
        OVERPAY = 4, _('余额支付')

    class OrderStatusChoices(models.IntegerChoices):
        TOBPAY = 1, _('待支付')
        TOBDELIVER = 2, _('待发货')
        TOBRECEIVED = 3, _('待收货')
        TOBEVALUATE = 4, _('待评价')
        COMPLETE = 5, _('已完成')
        CANCELLED = 6, _('已取消')

    owner = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name="用户",
        editable=False
    )
    order_sn = models.CharField(
        blank=True,
        default="",
        unique=True,
        max_length=32,
        editable=False,
        verbose_name="订单号",
        help_text="订单号"
    )
    trade_sn = models.CharField(
        blank=True, null=True,
        unique=True, max_length=64,
        verbose_name="交易号",
        help_text="交易号",
        editable=False
    )
    pay_status = models.IntegerField(
        choices=OrderStatusChoices.choices,
        default=1,
        verbose_name="支付状态",
        help_text="支付状态"
    )
    pay_method = models.IntegerField(
        choices=PayMethodChoices.choices,
        verbose_name="支付方式",
        help_text="支付方式",
        blank=True,
        null=True,
        editable=False
    )
    total_amount = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        verbose_name="商品总金额"
    )
    order_mark = models.CharField(
        blank=True,
        default="",
        max_length=100,
        verbose_name="订单备注",
        help_text="订单备注"
    )
    name = models.CharField("签收人", max_length=50, default="")
    phone = models.CharField("手机号", max_length=11, default="")
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    address = models.CharField("地址", max_length=200)
    pay_time = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="支付时间",
        help_text="支付时间",
        editable=False
    )

    class Meta:
        verbose_name = '订单信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.order_sn

    @classmethod
    def get_pay_method(cls):
        # 支付方式列表字典
        return dict(cls.PayMethodChoices.choices)

    @classmethod
    def get_pay_default(cls):
        # 获取支付方式的默认值
        return cls._meta.get_field('pay_method').default


class ShShopOrderSKU(AbstractModel):
    """订单商品"""
    order = models.ForeignKey(
        ShShopOrderInfo,
        on_delete=models.CASCADE,
        verbose_name="订单",
        editable=False
    )
    sku = models.ForeignKey(
        ShShopSKU,
        on_delete=models.PROTECT,
        blank=True,
        null=True,
        verbose_name="订单商品",
        editable=False
    )
    title = models.CharField("商品标题", max_length=200, blank=True, default="")
    desc = models.CharField("商品说明", max_length=200, blank=True, default="")
    spec = models.CharField("发布区域", max_length=200, blank=True, default="")
    content = models.TextField("商品详情", blank=True, default="")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField('单价', max_digits=18, decimal_places=2)
    is_commented = models.BooleanField(default=False, verbose_name="是否已评价")

    class Meta:
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

    def __str__(self) -> str:
        return self.sku.spu.title

shshop/module/cart/forms.py
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm

from shshop.models import ShShopingCart

class ShShopingCartForm(ModelForm):

    class Meta:
        model = ShShopingCart
        fields = ['sku', 'num']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

shshop/module/comments/forms.py
from django import forms

from shshop.models import ShOrderInfoComments


class ShOrderInfoCommentsModelForm(forms.ModelForm):

    class Meta:
        model = ShOrderInfoComments
        fields = ('content', 'comment_choices', 'object_id')
        widgets = {
            'content': forms.Textarea(attrs={"class":"textarea","rows": 5,  "placeholder":"请如实发表您对该商品的感受..."}),
        }

shshop/module/article/views.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :views.py
@说明    :用户消息视图
@时间    :2023/03/24 15:04:52
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''

from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from shshop.models import ShArticle, ShArticleCategory, ShArticleTags


class ArticleContext:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cates'] = self.get_cates()
        context['tags'] = self.get_tags()
        # context['archive'] = ShArticle.get_archive()
        context['tags_classes'] = ['is-danger', 'is-info', 'is-success', 'is-primary', 'is-light', 'is-black']
        return context

    def get_cates(self):
        return ShArticleCategory.objects.all()

    def get_tags(self):
        return ShArticleTags.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

    def get_stats(self, object_id):
        return ShArticle.get_stats(self.request, object_id)


class ShArticleListView(ArticleContext, ListView):
    """ 用户消息列表 """

    model = ShArticle
    template_name = "shshop/article/article_list.html"
    paginate_by = 15


class ShArticleDetailView(ArticleContext, DetailView):
    """ 用户消息详情 """
    model = ShArticle
    template_name = "shshop/article/article_detail.html"
    context_object_name = "article"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.pv = self.get_stats(obj.id).pv
        obj.uv = self.get_stats(obj.id).uv
        return obj


class ShArticleCategoryListView(ArticleContext, SingleObjectMixin, ListView):
    """ 分类用户消息列表 """

    paginate_by = 15
    template_name = "shshop/article/article_list.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=self.get_cates())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cate'] = self.object
        return context

    def get_queryset(self):
        queryset = self.object.sharticle_set.all()
        for qs in queryset:
            qs.pv = self.get_stats(qs.id).pv
            qs.uv = self.get_stats(qs.id).uv
        return queryset

shshop/module/cart/views.py
from django.views.generic import CreateView, ListView, View
from django.db.models import F
from django.db.utils import IntegrityError
from django.contrib import messages
from django.urls import reverse_lazy
from shshop.models import ShShopingCart, ShShopAddress
from shshop.public.mixins import (
    JsonableResponseMixin, JsonLoginRequiredMixin, JsonResponse,
    LoginRequiredMixin
)


class ShShopingCartCreateView(JsonLoginRequiredMixin, JsonableResponseMixin, CreateView):
    """ 加入购物车 """
    model = ShShopingCart
    fields = ['sku', 'num']
    success_url = reverse_lazy('shshop:carts')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        try:
            self.object = form.save()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
        except IntegrityError:
            carts = ShShopingCart.objects.filter(owner=self.request.user, sku=form.cleaned_data['sku'])
            carts.update(num=F('num')+int(form.cleaned_data['num']))
            self.object = carts.first()
            messages.add_message(self.request, messages.SUCCESS, f'已成功加入购物车！')
            return JsonResponse({'pk': self.object.id, 'code': 'ok', 'message': '已成功加入购物车！'}, json_dumps_params={'ensure_ascii': False})
        return super().form_valid(form)


class ShShopingCartListView(LoginRequiredMixin, ListView):

    template_name = "shshop/cart/carts.html"
    context_object_name = "carts"

    def get_queryset(self):
        queryset = ShShopingCart.objects.filter(owner=self.request.user)
        total = 0
        carts = []
        for cart in queryset:
            cart_dict = {}
            cart_dict['id'] = cart.id
            cart_dict['title'] = cart.sku.spu.title
            cart_dict['sku_id'] = cart.sku.id
            cart_dict['cover_pic'] = cart.sku.cover_pic.url
            cart_dict['options'] = list(cart.sku.options.values('name', 'spec__name'))
            cart_dict['price'] = cart.sku.price.to_eng_string()
            cart_dict['stock'] = cart.sku.stock
            cart_dict['sales'] = cart.num
            cart_dict['total_price'] = cart.num * cart.sku.price
            carts.append(cart_dict)
            total += cart.num * cart.sku.price
        return carts


class ShShopingCartUpdateView(JsonLoginRequiredMixin, View):
    """ 修改购物车数量 """

    def post(self, request, *args, **kwargs):
        cleaned_data = request.POST
        carts = ShShopingCart.objects.filter(owner=self.request.user, id=int(cleaned_data['id']))
        # 修改
        if carts.exists() and cleaned_data.get('actions') == 'update':
            carts.update(num=int(cleaned_data['num']))
            return JsonResponse({'code':'ok', 'message': '修改成功！'})
        # 删除
        elif carts.exists() and cleaned_data.get('actions') == 'delete':
            carts.delete()
            return JsonResponse({'code':'ok', 'message': '删除成功！'})
        else:
            return JsonResponse({'code':'err', 'message': '该购物不存在！'})

shshop/module/comments/views.py
from django.contrib.contenttypes.models import ContentType
from django.http.response import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages

from shshop.models import ShShopSKU, ShShopOrderSKU
from shshop.templatetags.shop_tags import commented_func
from shshop.module.order.views import ShShopOrderInfoDetailView
from shshop.module.comments.forms import ShOrderInfoCommentsModelForm


class ShOrderInfoCommentsFormView(ShShopOrderInfoDetailView):

    template_name = "shshop/comments/comments_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ShOrderInfoCommentsModelForm()
        return context

    def post(self, request, *args, **kwargs):

        # 判断评论时机
        if self.get_object().pay_status != 4:
            raise Http404

        form = ShOrderInfoCommentsModelForm(request.POST)
        content_type = ContentType.objects.get_for_model(ShShopSKU)
        form.instance.content_type = content_type
        form.instance.owner = request.user
        if form.is_valid():
            form.save()
            # 修改评论标志
            oskus = ShShopOrderSKU.objects.filter(
                    order=self.get_object(), sku__id=form.cleaned_data['object_id']
                )
            oskus.update(is_commented=True)
            # 修改订单状态
            if commented_func(self.get_object()):
                obj = self.get_object()
                obj.pay_status = 5
                obj.save()
            messages.add_message(request, messages.SUCCESS, f'评价发表成功！')
        return HttpResponseRedirect(f'{reverse("shshop:spu_detail", args=[oskus.first().sku.spu.id])}?tabsActive=comment')

shshop/module/order/views.py
from django.http.response import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from django.contrib import messages


from shshop.config.settings import sh_settings
from shshop.public.mixins import LoginRequiredMixin
from shshop.models import ShShopOrderInfo


class ShshopOrderInfoListView(LoginRequiredMixin, ListView):
    """ 订单列表 """
    model = ShShopOrderInfo
    template_name = "shshop/order/order_list.html"
    context_object_name = "order_list"
    paginate_by = sh_settings.USER_ORDERINFO_PAGINATE_BY
    paginate_orphans = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.request.GET.get('status') if self.request.GET.get('status') else ''
        return context

    def get_queryset(self):
        queryset = super().get_queryset().order_by('-add_date').filter(owner=self.request.user)
        cleaned_data = self.request.GET.dict()
        if cleaned_data and (cleaned_data.get('status') in ['1', '2', '3', '4', '5', '6']):
            queryset = queryset.filter(pay_status=int(cleaned_data['status']))
        return queryset

    def post(self, request, *args, **kwargs):
        orders = ShShopOrderInfo.objects.filter(owner=request.user, order_sn=request.POST['order_sn'])
        orders.update(pay_status=4)
        messages.add_message(request, messages.SUCCESS, f'订单{orders.first()}已确认收货！')
        return HttpResponseRedirect(f"{request.path}?status=4")


class ShShopOrderInfoDetailView(LoginRequiredMixin, DetailView):
    """ 订单结算支付 """

    model = ShShopOrderInfo
    template_name = "shshop/order/order_detail.html"
    context_object_name = "order"
    slug_field="order_sn"

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pay_methods'] = self.get_pay_methods()
        return context

    def get_pay_methods(self):
        pay_methods = ShShopOrderInfo.get_pay_method()
        pay_list = [
            {
                'value': 1,
                'name': pay_methods[1],
                'icon': "/static/shshop/img/hdpay.svg",
                'is_default': False,
            },
            {
                'value': 4,
                'name': pay_methods[4],
                'icon': "/static/shshop/img/ye.svg",
                'is_default': False,
            }
        ]
        return pay_list


class ShShopOrderInfoUserDetailView(ShShopOrderInfoDetailView):

    template_name = "shshop/order/user_order_detail.html"

shshop/templates/shshop/payment/alipay_notify.html
{% extends 'shshop/order/order_detail.html' %}

{% load static %}
{% block title %}支付结果反馈{% endblock %}

{% block breadcrumb %}
<div class="container">
  <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'shshop:home' %}">首页</a></li>
      <li class="is-active"><a href="#" aria-current="page">支付结果反馈</a></li>
    </ul>
  </nav>
</div>
{% endblock %}


{% block payok %}
{% include 'shshop/payment/payok.html' %}
{% comment %} <div class="box is-radiusless is-marginless pl-6 pr-6" style="line-height: 30px;">

    <div class="is-flex is-flex-direction-column is-align-items-center mb-4">
        <figure class="image is-128x128">
        <img src="{% static 'shshop/img/payok.svg' %}">
        </figure>
        <h1 class=" is-size-3 ">支付成功</h1>
    </div>
    <div class=" dropdown-divider"></div>

    <p>订单编号：{{ order.order_sn }}</p>
    <p>实际支付：{{ order.total_amount }}元</p>
    <p>收货信息：{{ order.address }}</p>
    <p>支付状态：{{ order.get_pay_status_display }}</p>
    <p>支付方式：{{ order.get_pay_method_display }}</p>
    <p>支付时间：{{ order.pay_time }}</p>
    <p>订单商品：</p>
    <div class=" dropdown-divider"></div>
    <ul>
        {% for order_sku in order.shshopordersku_set.all %}
            <li><a>{{ order_sku.title }} <br> {{ order_sku.spec }}</a></li>
            <div class=" dropdown-divider"></div>
        {% endfor %}
    </ul>
</div>

<div class="box is-radiusless">
    <div class=" buttons is-justify-content-center">
    <a class=" button is-success" href="{% url 'shshop:order_detail' order.order_sn %}">查看订单</a>
    <a class=" button is-black" href="{% url 'shshop:home' %}">返回首页</a>
    </div>
</div> {% endcomment %}
{% endblock %}

{% block vue %}{% endblock %}

shshop/templates/shshop/payment/cash_register.html
{% extends 'shshop/base_site.html' %}

{% load static shop_tags %}

{% block title %}结算中心{% endblock %}

{% block extrastyle %}
<script src="{% static 'shshop/js/axios.min.js' %}"></script>
<script src="{% static 'shshop/js/request.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
<div class="container">
  <nav class="breadcrumb is-marginless mt-3 mb-3 is-small" aria-label="breadcrumbs">
    <ul>
      <li><a href="{% url 'shshop:home' %}">首页</a></li>
      <li><a href="{% url 'shshop:carts' %}">购物车</a></li>
      <li class="is-active"><a href="#" aria-current="page">订单确认</a></li>
    </ul>
  </nav>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        {% address_result request.user %}

        <div class="box is-marginless is-radiusless" id="saveOrder">
            <h1 class="is-size-5">订单商品</h1>
            <div class=" dropdown-divider"></div>
            {% for cart in carts %}
            <div class="columns">
                <div class="column is-2 is-flex is-justify-content-center">
                    <figure class="image is-128x128">
                        {% if cart.spu %}
                        <img src="{{ cart.cover_pic.url }}" alt="{{ cart.spu.title }}">
                        {% else %}
                        <img src="{{ cart.sku.cover_pic.url }}" alt="{{ cart.sku.spu.title }}">
                        {% endif %}
                    </figure>
                </div>
                <div class="column is-flex is-flex-direction-column is-justify-content-center">
                    {% if cart.spu %}
                    <h1 class=" has-text-weight-bold">{{ cart.spu.title }}</h1>
                        {% if cart.options.all %}
                            <span class="has-text-grey-light"> 规格：{{ cart.options.all|join:' ' }}</span>
                        {% endif %}
                    {% else %}
                        <h1 class=" has-text-weight-bold">{{ cart.sku.spu.title }}</h1>

                        {% if cart.sku.options.all %}
                        <span class="has-text-grey-light"> 规格：{{ cart.sku.options.all|join:' ' }}</span>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
                    {% if cart.spu %}¥{{ cart.price  }} x {{ cart.num }}{% else %}¥{{ cart.sku.price}} x {{ cart.num }}{% endif %}
                </div>
                <div class="column is-2 is-flex is-justify-content-center is-align-items-center">
                    ¥{{ cart.total_price }}
                </div>

            </div>
            <div class="dropdown-divider"></div>
            {% empty %}
            未选择任何商品！
            {% endfor %}

            {% if carts %}
            <!-- 订单留言 -->
            <div class="box is-shadowless is-radiusless has-background-light">
                <div class="field">
                    <label class="label">订单留言</label>
                    <div class="control">
                        <textarea class="textarea" v-model="mark" placeholder="请备注说明您的特殊要求..."></textarea>
                    </div>
                </div>
            </div>

            <!-- 付款信息 -->
            <div class="is-flex is-flex-direction-column">
                <div class="is-flex mb-2">
                    <div class=" has-text-right" style="width:85%">{{ count }} 件商品，总商品金额：</div>
                    <div class=" has-text-left" style="width:10%; margin-left:5%;">¥{{ total }} </div>
                </div>
                <div class="is-flex mb-2">
                    <div class="has-text-right" style="width:85%">运费：</div>
                    <div class="has-text-left" style="width:10%;margin-left:5%;">¥{{ freight }} </div>
                </div>
                <div class="is-flex has-text-danger-dark">
                    <div class=" has-text-right is-size-5" style="width:85%">应付总额：</div>
                    <div class=" has-text-left is-size-5" style="width:10%; margin-left:5%;">¥{{ pay_total }} </div>
                </div>
            </div>
            <div class=" dropdown-divider"></div>
            <div class="has-text-right">
                <button class="button is-primary mt-2 pl-6 pr-6 mr-6 is-large" @click="paySave">提交订单</button>
            </div>
            {% endif %}
        </div>


    </div>

{% endblock %}


{% block vue %}
    <script>
        var saveOrder = new Vue({
            el: '#saveOrder',
            delimiters: ['{$', '$}'],
            data:{
                mark: ""
            },
            methods:{
                paySave(){
                    if (!address._data.formProps.id){
                        navbar.toastMessage('is-danger', '请选择有效收货地址！')
                        return
                    }

                    // 提交订单
                    const sendData = new FormData()
                    sendData.append('addr_id', address._data.formProps.id)
                    sendData.append('order_mark', this.mark)
                    request({
                        method: 'post',
                        url: `{% url "shshop:cash_register" %}`,
                        headers: {'Accept': 'application/json'},
                        data: sendData
                    }).then(res => {
                        if (res.data.code == 'ok') {
                            navbar.toastMessage('is-success', res.data.message)
                            location.href = res.data.pay_url
                        }else{
                            navbar.toastMessage('is-danger', res.data.message)
                        }
                    })
                }
            }
        })
    </script>
{% endblock %}

shshop/templates/shshop/payment/payok.html
{% load static %}

<div class="box is-radiusless is-marginless pl-6 pr-6" style="line-height: 30px;">

    <div class="is-flex is-flex-direction-column is-align-items-center mb-4">
        <figure class="image is-128x128">
        <img src="{% static 'shshop/img/payok.svg' %}">
        </figure>
        <h1 class=" is-size-3 ">支付成功</h1>
    </div>
    <div class=" dropdown-divider"></div>

    <p>订单编号：{{ order.order_sn }}</p>
    <p>实际支付：{{ order.total_amount }}元</p>
    <p>收货信息：{{ order.address }}</p>
    <p>支付状态：{{ order.get_pay_status_display }}</p>
    <p>支付方式：{{ order.get_pay_method_display }}</p>
    <p>支付时间：{{ order.pay_time }}</p>
    <p>订单商品：</p>
    <div class=" dropdown-divider"></div>
    <ul>
        {% for order_sku in order.shshopordersku_set.all %}
            <li><a>{{ order_sku.title }} <br> {{ order_sku.spec }}</a></li>
            <div class=" dropdown-divider"></div>
        {% endfor %}
    </ul>
</div>

<div class="box is-radiusless">
    <div class=" buttons is-justify-content-center">
    <a class=" button is-success" href="{% url 'shshop:user_order_detail' order.order_sn %}">查看订单</a>
    <a class=" button is-black" href="{% url 'shshop:home' %}">返回首页</a>
    </div>
</div>